---
require: rubocop-rspec

AllCops:
  DisplayStyleGuide: true
  DisplayCopNames: true
  TargetRubyVersion: 2.2
  Exclude:
    - bin/*

Layout/DotPosition:
  EnforcedStyle: leading
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Max: 120
  Exclude:
    - spec/**/*

Naming/FileName:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
  Enabled: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
